version: '3.8'
services:
  postgres_viva: # nombre servicio
    build: .
    container_name: contenedor-postgres-viva
    restart: always
    command: ["postgres",
      "-c", "shared_preload_libraries=pg_stat_statements,pgaudit",
      "-c", "log_connections=on",
      "-c", "log_statement=ddl",
      "-c", "pgaudit.log=write,ddl",
      "-c", "pgaudit.log_relation=on",
      "-c", "pgaudit.log_parameter=on",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf"
    ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tbdviva
      POSTGRES_DB: bd-viva
      TZ: America/La_Paz
    ports:
      - "5433:5432"
    volumes:
      - ./datos_postgres_viva:/var/lib/postgresql/data
      - ./07-scripts-iniciales:/docker-entrypoint-initdb.d
      - ./08-scripts-semilla:/seeds
      - ./11-configuracion-de-seguridad/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    networks:
      - red_viva

networks:
  red_viva:
    external: true