# -----------------------------
# PostgreSQL configuration file
# -----------------------------

# CONNECTION SETTINGS
listen_addresses = '*'
port = 5432
max_connections = 100

# SECURITY & AUTHENTICATION
password_encryption = scram-sha-256

# LOGGING
log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'

# NOTA: Los parámetros de pgAudit y log_statement 
# se pasan directamente mediante parámetros -c en el docker-compose.yml
# para asegurar que siempre tengan precedencia.
