-- =============================================================
-- DDL - BASE DE DATOS VIVA
-- 
--   1. Extension pgcrypto con una sola línea limpia
--   2. CREATE SCHEMA IF NOT EXISTS únicos (sin duplicados)
--   3. Funciones $libdir/pgcrypto eliminadas
--   4. CREATE SEQUENCE manuales eliminados (serial4 los gestiona)
--   5. Permisos de secuencias consolidados con GRANT ON ALL SEQUENCES
--   6. ENABLE ROW LEVEL SECURITY añadido en finanzas."Factura"
--   7. Restricciones CHECK simplificadas a sintaxis IN (...)
--   8. Todas las FOREIGN KEY cruzadas entre esquemas movidas al final
-- =============================================================


-- =============================================================
-- BLOQUE 0: EXTENSIONES
-- =============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public;


-- =============================================================
-- BLOQUE 1: PRE-CREACIÓN DE ESQUEMAS (únicos, con IF NOT EXISTS)
-- =============================================================

CREATE SCHEMA IF NOT EXISTS clientes     AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS comercial    AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS fidelizacion AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS finanzas     AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS lineas       AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS seguridad    AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS servicios    AUTHORIZATION postgres;


-- =============================================================
-- BLOQUE 2: TABLAS - ESQUEMA clientes
-- =============================================================

CREATE TABLE clientes."Cliente" (
    id_cliente  int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_registro timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    estado varchar(20) DEFAULT 'Activo'::character varying NULL,
    ciudad varchar(50) NULL,
    CONSTRAINT "Cliente_pkey" PRIMARY KEY (id_cliente)
);

ALTER TABLE clientes."Cliente" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE clientes."Cliente" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE clientes."Cliente" TO rol_app;
GRANT SELECT ON TABLE clientes."Cliente" TO rol_comercial;
GRANT SELECT ON TABLE clientes."Cliente" TO rol_reporte;


CREATE TABLE clientes."Empresa" (
    id_empresa       int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_cliente       int4 NULL,
    razon_social     varchar(150) NOT NULL,
    nit              varchar(20) NOT NULL,
    representante_legal varchar(100) NULL,
    CONSTRAINT "Empresa_id_cliente_key" UNIQUE (id_cliente),
    CONSTRAINT "Empresa_nit_key" UNIQUE (nit),
    CONSTRAINT "Empresa_pkey" PRIMARY KEY (id_empresa)
);

ALTER TABLE clientes."Empresa" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE clientes."Empresa" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE clientes."Empresa" TO rol_app;
GRANT SELECT ON TABLE clientes."Empresa" TO rol_comercial;
GRANT SELECT ON TABLE clientes."Empresa" TO rol_reporte;


CREATE TABLE clientes."Persona_Natural" (
    id_persona  int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_cliente  int4 NULL,
    nombre      varchar(100) NOT NULL,
    apellido    varchar(100) NOT NULL,
    ci          varchar(20) NOT NULL,
    correo      varchar(100) NULL,
    CONSTRAINT "Persona_Natural_ci_key" UNIQUE (ci),
    CONSTRAINT "Persona_Natural_id_cliente_key" UNIQUE (id_cliente),
    CONSTRAINT "Persona_Natural_pkey" PRIMARY KEY (id_persona)
);

ALTER TABLE clientes."Persona_Natural" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE clientes."Persona_Natural" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE clientes."Persona_Natural" TO rol_app;
GRANT SELECT ON TABLE clientes."Persona_Natural" TO rol_comercial;
GRANT SELECT ON TABLE clientes."Persona_Natural" TO rol_reporte;

-- Permisos de esquema
GRANT ALL ON SCHEMA clientes TO postgres;
GRANT USAGE ON SCHEMA clientes TO rol_app;
GRANT USAGE ON SCHEMA clientes TO rol_comercial;
GRANT USAGE ON SCHEMA clientes TO rol_reporte;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA clientes TO rol_app;


-- =============================================================
-- BLOQUE 3: TABLAS - ESQUEMA comercial
-- =============================================================

CREATE TABLE comercial."Promocion" (
    id_promocion   int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_promo   varchar(100) NOT NULL,
    descripcion    text NULL,
    fecha_inicio   timestamp NOT NULL,
    fecha_fin      timestamp NOT NULL,
    CONSTRAINT "Promocion_pkey" PRIMARY KEY (id_promocion)
);

ALTER TABLE comercial."Promocion" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE comercial."Promocion" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE comercial."Promocion" TO rol_comercial;
GRANT SELECT ON TABLE comercial."Promocion" TO rol_reporte;


CREATE TABLE comercial."Condicion_Promocion" (
    id_condicion          int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_promocion          int4 NOT NULL,
    descripcion_condicion text NOT NULL,
    CONSTRAINT "Condicion_Promocion_pkey" PRIMARY KEY (id_condicion),
    CONSTRAINT fk_cpr_pro FOREIGN KEY (id_promocion) REFERENCES comercial."Promocion"(id_promocion) ON DELETE CASCADE
);

ALTER TABLE comercial."Condicion_Promocion" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE comercial."Condicion_Promocion" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE comercial."Condicion_Promocion" TO rol_comercial;
GRANT SELECT ON TABLE comercial."Condicion_Promocion" TO rol_reporte;


-- FK cruzadas hacia lineas."Linea" declaradas más abajo en el bloque final
CREATE TABLE comercial."Numero_Amigo" (
    id_numero_amigo int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea_origen int4 NOT NULL,
    id_linea_destino int4 NOT NULL,
    id_promo_linea  int4 NOT NULL,
    CONSTRAINT "Numero_Amigo_pkey" PRIMARY KEY (id_numero_amigo)
);

ALTER TABLE comercial."Numero_Amigo" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE comercial."Numero_Amigo" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE comercial."Numero_Amigo" TO rol_comercial;
GRANT SELECT ON TABLE comercial."Numero_Amigo" TO rol_reporte;


-- FK cruzada hacia lineas."Linea" declarada más abajo en el bloque final
CREATE TABLE comercial."Promocion_Linea" (
    id_promo_linea    int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_promocion      int4 NOT NULL,
    id_linea          int4 NOT NULL,
    fecha_aplicacion  timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT "Promocion_Linea_pkey" PRIMARY KEY (id_promo_linea),
    CONSTRAINT fk_prl_pro FOREIGN KEY (id_promocion) REFERENCES comercial."Promocion"(id_promocion)
);

ALTER TABLE comercial."Promocion_Linea" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE comercial."Promocion_Linea" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE comercial."Promocion_Linea" TO rol_comercial;
GRANT SELECT ON TABLE comercial."Promocion_Linea" TO rol_reporte;

-- Permisos de esquema
GRANT ALL ON SCHEMA comercial TO postgres;
GRANT USAGE ON SCHEMA comercial TO rol_comercial;
GRANT USAGE ON SCHEMA comercial TO rol_reporte;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA comercial TO rol_comercial;


-- =============================================================
-- BLOQUE 4: TABLAS - ESQUEMA fidelizacion
-- =============================================================

CREATE TABLE fidelizacion."Condicion_Puntos" (
    id_condicion      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion       text NOT NULL,
    puntos_otorgados  int4 NOT NULL,
    CONSTRAINT "Condicion_Puntos_pkey" PRIMARY KEY (id_condicion)
);

ALTER TABLE fidelizacion."Condicion_Puntos" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE fidelizacion."Condicion_Puntos" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE fidelizacion."Condicion_Puntos" TO rol_comercial;
GRANT SELECT ON TABLE fidelizacion."Condicion_Puntos" TO rol_reporte;
GRANT SELECT ON TABLE fidelizacion."Condicion_Puntos" TO rol_auditor;


-- FK cruzadas hacia lineas."Linea" declaradas más abajo en el bloque final
CREATE TABLE fidelizacion."Historial_Puntos" (
    id_historial      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea          int4 NOT NULL,
    id_condicion      int4 NOT NULL,
    id_linea_invitada int4 NULL,
    puntos_afectados  int4 NOT NULL,
    fecha_movimiento  timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT "Historial_Puntos_pkey" PRIMARY KEY (id_historial),
    CONSTRAINT fk_hpu_con FOREIGN KEY (id_condicion) REFERENCES fidelizacion."Condicion_Puntos"(id_condicion)
);

ALTER TABLE fidelizacion."Historial_Puntos" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE fidelizacion."Historial_Puntos" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE fidelizacion."Historial_Puntos" TO rol_comercial;
GRANT SELECT ON TABLE fidelizacion."Historial_Puntos" TO rol_reporte;
GRANT SELECT ON TABLE fidelizacion."Historial_Puntos" TO rol_auditor;


-- FK cruzada hacia lineas."Linea" declarada más abajo en el bloque final
CREATE TABLE fidelizacion."Puntos_Bonus" (
    id_puntos          int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea           int4 NOT NULL,
    cantidad_acumulada int4 DEFAULT 0 NULL,
    CONSTRAINT "Puntos_Bonus_id_linea_key" UNIQUE (id_linea),
    CONSTRAINT "Puntos_Bonus_pkey" PRIMARY KEY (id_puntos)
);

ALTER TABLE fidelizacion."Puntos_Bonus" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE fidelizacion."Puntos_Bonus" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE fidelizacion."Puntos_Bonus" TO rol_comercial;
GRANT SELECT ON TABLE fidelizacion."Puntos_Bonus" TO rol_reporte;
GRANT SELECT ON TABLE fidelizacion."Puntos_Bonus" TO rol_auditor;

-- Permisos de esquema
GRANT ALL ON SCHEMA fidelizacion TO postgres;
GRANT USAGE ON SCHEMA fidelizacion TO rol_comercial;
GRANT USAGE ON SCHEMA fidelizacion TO rol_reporte;
GRANT USAGE ON SCHEMA fidelizacion TO rol_auditor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA fidelizacion TO rol_comercial;


-- =============================================================
-- BLOQUE 5: TABLAS - ESQUEMA finanzas
-- =============================================================

-- FK cruzada hacia lineas."Linea" declarada más abajo en el bloque final
CREATE TABLE finanzas."Bolsillo" (
    id_bolsillo     int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea        int4 NOT NULL,
    saldo_dinero    numeric(10, 2) DEFAULT 0.00 NULL,
    saldo_megas     int4 DEFAULT 0 NULL,
    saldo_minutos   int4 DEFAULT 0 NULL,
    saldo_sms       int4 DEFAULT 0 NULL,
    CONSTRAINT "Bolsillo_id_linea_key" UNIQUE (id_linea),
    CONSTRAINT "Bolsillo_pkey" PRIMARY KEY (id_bolsillo)
);

ALTER TABLE finanzas."Bolsillo" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Bolsillo" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Bolsillo" TO rol_app;
GRANT SELECT ON TABLE finanzas."Bolsillo" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Bolsillo" TO rol_auditor;


-- FK cruzada hacia lineas."Linea" declarada más abajo en el bloque final
CREATE TABLE finanzas."Factura" (
    id_factura        int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea          int4 NOT NULL,
    monto_total       numeric(10, 2) NOT NULL,
    fecha_emision     timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    fecha_vencimiento timestamp NOT NULL,
    estado_pago       varchar(20) DEFAULT 'Pendiente'::character varying NULL,
    CONSTRAINT "Factura_pkey" PRIMARY KEY (id_factura)
);

ALTER TABLE finanzas."Factura" ENABLE ROW LEVEL SECURITY;

CREATE POLICY factura_propia_policy ON finanzas."Factura"
    AS PERMISSIVE
    FOR SELECT
    TO rol_app
    USING ((id_linea = (NULLIF(current_setting('app.current_linea_id'::text, true), ''::text))::integer));

CREATE POLICY factura_admin_policy ON finanzas."Factura"
    AS PERMISSIVE
    FOR ALL
    TO rol_finanzas, rol_reporte, rol_auditor
    USING (true) WITH CHECK (true);

ALTER TABLE finanzas."Factura" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Factura" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Factura" TO rol_app;
GRANT SELECT ON TABLE finanzas."Factura" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Factura" TO rol_auditor;


CREATE TABLE finanzas."Tarjeta_Recarga" (
    id_tarjeta      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_pin      varchar(20) NOT NULL,
    monto           numeric(10, 2) NOT NULL,
    estado          varchar(20) DEFAULT 'Disponible'::character varying NULL,
    id_linea_cargada int4 NULL,
    CONSTRAINT "Tarjeta_Recarga_codigo_pin_key" UNIQUE (codigo_pin),
    CONSTRAINT "Tarjeta_Recarga_pkey" PRIMARY KEY (id_tarjeta)
);

ALTER TABLE finanzas."Tarjeta_Recarga" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Tarjeta_Recarga" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Tarjeta_Recarga" TO rol_app;
GRANT SELECT ON TABLE finanzas."Tarjeta_Recarga" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Tarjeta_Recarga" TO rol_auditor;


-- FK cruzadas hacia lineas."Linea" declaradas más abajo en el bloque final
CREATE TABLE finanzas."Recarga" (
    id_recarga    int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea      int4 NOT NULL,
    monto         numeric(10, 2) NOT NULL,
    fecha_recarga timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    id_tarjeta    int4 NULL,
    aplicar_bono  boolean DEFAULT false,
    CONSTRAINT "Recarga_pkey" PRIMARY KEY (id_recarga),
    CONSTRAINT fk_rec_tar FOREIGN KEY (id_tarjeta) REFERENCES finanzas."Tarjeta_Recarga"(id_tarjeta)
);

ALTER TABLE finanzas."Recarga" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Recarga" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Recarga" TO rol_app;
GRANT SELECT ON TABLE finanzas."Recarga" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Recarga" TO rol_auditor;


-- FK cruzada hacia lineas."Linea" declarada más abajo en el bloque final
CREATE TABLE finanzas."T_Presta" (
    id_prestamo     int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea        int4 NOT NULL,
    monto_prestado  numeric(10, 2) NOT NULL,
    monto_comision  numeric(10, 2) NOT NULL,
    estado_cobro    varchar(20) DEFAULT 'Pendiente'::character varying NULL,
    CONSTRAINT "T_Presta_pkey" PRIMARY KEY (id_prestamo)
);

ALTER TABLE finanzas."T_Presta" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."T_Presta" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."T_Presta" TO rol_app;
GRANT SELECT ON TABLE finanzas."T_Presta" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."T_Presta" TO rol_auditor;


-- FK cruzadas hacia lineas."Linea" declaradas más abajo en el bloque final
CREATE TABLE finanzas."Transaccion" (
    id_transaccion   int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea         int4 NOT NULL,
    tipo_transaccion varchar(50) NOT NULL,
    monto            numeric(10, 2) NOT NULL,
    fecha            timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT "Transaccion_pkey" PRIMARY KEY (id_transaccion)
);

ALTER TABLE finanzas."Transaccion" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Transaccion" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Transaccion" TO rol_app;
GRANT SELECT ON TABLE finanzas."Transaccion" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Transaccion" TO rol_auditor;


-- FK cruzadas hacia lineas."Linea" declaradas más abajo en el bloque final
CREATE TABLE finanzas."Transfuzion" (
    id_transfuzion      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea_origen     int4 NOT NULL,
    id_linea_destino    int4 NOT NULL,
    monto_transferido   numeric(10, 2) NOT NULL,
    fecha               timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT "Transfuzion_pkey" PRIMARY KEY (id_transfuzion)
);

ALTER TABLE finanzas."Transfuzion" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE finanzas."Transfuzion" TO postgres;
GRANT INSERT, SELECT, UPDATE ON TABLE finanzas."Transfuzion" TO rol_app;
GRANT SELECT ON TABLE finanzas."Transfuzion" TO rol_reporte;
GRANT SELECT ON TABLE finanzas."Transfuzion" TO rol_auditor;

-- Permisos de esquema
GRANT ALL ON SCHEMA finanzas TO postgres;
GRANT USAGE ON SCHEMA finanzas TO rol_app;
GRANT USAGE ON SCHEMA finanzas TO rol_reporte;
GRANT USAGE ON SCHEMA finanzas TO rol_auditor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA finanzas TO rol_app;


-- =============================================================
-- BLOQUE 6: TABLAS - ESQUEMA lineas  (tabla núcleo referenciada por todos)
-- =============================================================

CREATE TABLE lineas."Equipo" (
    id_equipo int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    imei      varchar(15) NOT NULL,
    marca     varchar(50) NULL,
    modelo    varchar(50) NULL,
    CONSTRAINT "Equipo_imei_key" UNIQUE (imei),
    CONSTRAINT "Equipo_pkey" PRIMARY KEY (id_equipo)
);

ALTER TABLE lineas."Equipo" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."Equipo" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."Equipo" TO rol_app;
GRANT SELECT ON TABLE lineas."Equipo" TO rol_reporte;


CREATE TABLE lineas."Plan" (
    id_plan         int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_plan     varchar(50) NOT NULL,
    tarifa_mensual  numeric(10, 2) NOT NULL,
    tipo_plan       varchar(20) NULL,
    CONSTRAINT "Plan_pkey" PRIMARY KEY (id_plan),
    CONSTRAINT "Plan_tipo_plan_check" CHECK (tipo_plan IN ('Prepago', 'Postpago'))
);

ALTER TABLE lineas."Plan" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."Plan" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."Plan" TO rol_app;
GRANT SELECT ON TABLE lineas."Plan" TO rol_reporte;


CREATE TABLE lineas."SIM_Card" (
    id_sim  int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    iccid   varchar(20) NOT NULL,
    imsi    varchar(20) NOT NULL,
    estado  varchar(20) DEFAULT 'Disponible'::character varying NULL,
    CONSTRAINT "SIM_Card_iccid_key" UNIQUE (iccid),
    CONSTRAINT "SIM_Card_imsi_key" UNIQUE (imsi),
    CONSTRAINT "SIM_Card_pkey" PRIMARY KEY (id_sim)
);

ALTER TABLE lineas."SIM_Card" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."SIM_Card" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."SIM_Card" TO rol_app;
GRANT SELECT ON TABLE lineas."SIM_Card" TO rol_reporte;


CREATE TABLE lineas."Linea" (
    id_linea        int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    numero_telefono varchar(15) NOT NULL,
    id_cliente      int4 NOT NULL,
    id_plan         int4 NOT NULL,
    id_sim_activo   int4 NOT NULL,
    estado          varchar(20) DEFAULT 'Activa'::character varying NULL,
    CONSTRAINT "Linea_id_sim_activo_key" UNIQUE (id_sim_activo),
    CONSTRAINT "Linea_numero_telefono_key" UNIQUE (numero_telefono),
    CONSTRAINT "Linea_pkey" PRIMARY KEY (id_linea),
    CONSTRAINT fk_lin_plan FOREIGN KEY (id_plan) REFERENCES lineas."Plan"(id_plan),
    CONSTRAINT fk_lin_sim  FOREIGN KEY (id_sim_activo) REFERENCES lineas."SIM_Card"(id_sim)
);

ALTER TABLE lineas."Linea" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."Linea" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."Linea" TO rol_app;
GRANT SELECT ON TABLE lineas."Linea" TO rol_reporte;


CREATE TABLE lineas."Historial_Linea_Equipo" (
    id_historial     int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea         int4 NOT NULL,
    id_equipo        int4 NOT NULL,
    fecha_asociacion timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT "Historial_Linea_Equipo_pkey" PRIMARY KEY (id_historial),
    CONSTRAINT fk_hle_eq  FOREIGN KEY (id_equipo) REFERENCES lineas."Equipo"(id_equipo),
    CONSTRAINT fk_hle_lin FOREIGN KEY (id_linea)  REFERENCES lineas."Linea"(id_linea)
);

ALTER TABLE lineas."Historial_Linea_Equipo" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."Historial_Linea_Equipo" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."Historial_Linea_Equipo" TO rol_app;
GRANT SELECT ON TABLE lineas."Historial_Linea_Equipo" TO rol_reporte;


CREATE TABLE lineas."Linea_Postpago" (
    id_postpago     int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea        int4 NOT NULL,
    limite_credito  numeric(10, 2) NOT NULL,
    dia_corte       int4 NULL,
    CONSTRAINT "Linea_Postpago_dia_corte_check" CHECK ((dia_corte >= 1) AND (dia_corte <= 31)),
    CONSTRAINT "Linea_Postpago_id_linea_key" UNIQUE (id_linea),
    CONSTRAINT "Linea_Postpago_pkey" PRIMARY KEY (id_postpago),
    CONSTRAINT fk_pos_lin FOREIGN KEY (id_linea) REFERENCES lineas."Linea"(id_linea) ON DELETE CASCADE
);

ALTER TABLE lineas."Linea_Postpago" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE lineas."Linea_Postpago" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE lineas."Linea_Postpago" TO rol_app;
GRANT SELECT ON TABLE lineas."Linea_Postpago" TO rol_reporte;

-- Permisos de esquema
GRANT ALL ON SCHEMA lineas TO postgres;
GRANT USAGE ON SCHEMA lineas TO rol_app;
GRANT USAGE ON SCHEMA lineas TO rol_reporte;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA lineas TO rol_app;


-- =============================================================
-- BLOQUE 7: TABLAS - ESQUEMA seguridad
-- =============================================================

CREATE TABLE seguridad."Auditoria" (
    id_auditoria   int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tabla_afectada varchar(100) NOT NULL,
    operacion      varchar(20) NOT NULL,
    usuario_db     varchar(50) DEFAULT CURRENT_USER NULL,
    fecha          timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    detalle_cambio text NULL,
    CONSTRAINT "Auditoria_pkey" PRIMARY KEY (id_auditoria)
);

ALTER TABLE seguridad."Auditoria" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE seguridad."Auditoria" TO postgres;
GRANT SELECT ON TABLE seguridad."Auditoria" TO rol_auditor;


CREATE TABLE seguridad."Usuario_Sistema" (
    id_usuario    int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      varchar(50) NOT NULL,
    password_hash varchar(255) NOT NULL,
    id_cliente    int4 NULL,
    CONSTRAINT "Usuario_Sistema_id_cliente_key" UNIQUE (id_cliente),
    CONSTRAINT "Usuario_Sistema_pkey" PRIMARY KEY (id_usuario),
    CONSTRAINT "Usuario_Sistema_username_key" UNIQUE (username)
);

ALTER TABLE seguridad."Usuario_Sistema" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE seguridad."Usuario_Sistema" TO postgres;
GRANT SELECT ON TABLE seguridad."Usuario_Sistema" TO rol_auditor;

-- Permisos de esquema
GRANT ALL ON SCHEMA seguridad TO postgres;
GRANT USAGE ON SCHEMA seguridad TO rol_auditor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA seguridad TO rol_auditor;


-- =============================================================
-- BLOQUE 8: TABLAS - ESQUEMA servicios
-- =============================================================

CREATE TABLE servicios."Paquete" (
    id_paquete     int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre_paquete varchar(50) NOT NULL,
    costo          numeric(10, 2) NOT NULL,
    duracion_dias  int4 NOT NULL,
    CONSTRAINT "Paquete_pkey" PRIMARY KEY (id_paquete)
);

ALTER TABLE servicios."Paquete" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE servicios."Paquete" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE servicios."Paquete" TO rol_app;
GRANT SELECT ON TABLE servicios."Paquete" TO rol_reporte;


CREATE TABLE servicios."App_Exenta_En_Bolsa" (
    id_app      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_paquete  int4 NOT NULL,
    nombre_app  varchar(50) NOT NULL,
    CONSTRAINT "App_Exenta_En_Bolsa_pkey" PRIMARY KEY (id_app),
    CONSTRAINT fk_aeb_paq FOREIGN KEY (id_paquete) REFERENCES servicios."Paquete"(id_paquete) ON DELETE CASCADE
);

ALTER TABLE servicios."App_Exenta_En_Bolsa" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE servicios."App_Exenta_En_Bolsa" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE servicios."App_Exenta_En_Bolsa" TO rol_app;
GRANT SELECT ON TABLE servicios."App_Exenta_En_Bolsa" TO rol_reporte;


-- FK cruzadas hacia lineas."Linea" y servicios."Paquete" declaradas más abajo
CREATE TABLE servicios."Bolsa_Activa" (
    id_bolsa_activa  int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea         int4 NOT NULL,
    id_paquete       int4 NOT NULL,
    fecha_activacion timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    fecha_expiracion timestamp NOT NULL,
    CONSTRAINT "Bolsa_Activa_pkey" PRIMARY KEY (id_bolsa_activa),
    CONSTRAINT fk_bac_paq FOREIGN KEY (id_paquete) REFERENCES servicios."Paquete"(id_paquete)
);

ALTER TABLE servicios."Bolsa_Activa" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE servicios."Bolsa_Activa" TO postgres;
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLE servicios."Bolsa_Activa" TO rol_app;
GRANT SELECT ON TABLE servicios."Bolsa_Activa" TO rol_reporte;


-- FK cruzadas hacia lineas."Linea" y servicios."Bolsa_Activa" declaradas más abajo
CREATE TABLE servicios."Consumo" (
    id_consumo      int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_linea        int4 NOT NULL,
    tipo_consumo    varchar(20) NULL,
    cantidad        numeric(10, 2) NOT NULL,
    fecha_consumo   timestamp DEFAULT CURRENT_TIMESTAMP NULL,
    id_bolsa_activa int4 NULL,
    CONSTRAINT "Consumo_pkey" PRIMARY KEY (id_consumo),
    CONSTRAINT "Consumo_tipo_consumo_check" CHECK (tipo_consumo IN ('Datos', 'Voz', 'SMS')),
    CONSTRAINT fk_con_bol FOREIGN KEY (id_bolsa_activa) REFERENCES servicios."Bolsa_Activa"(id_bolsa_activa)
);

ALTER TABLE servicios."Consumo" ENABLE ROW LEVEL SECURITY;

CREATE POLICY consumo_propio_policy ON servicios."Consumo"
    AS PERMISSIVE
    FOR SELECT
    TO rol_app
    USING ((id_linea = (NULLIF(current_setting('app.current_linea_id'::text, true), ''::text))::integer));

CREATE POLICY consumo_propio_insert_policy ON servicios."Consumo"
    AS PERMISSIVE
    FOR INSERT
    TO rol_app
    WITH CHECK ((id_linea = (NULLIF(current_setting('app.current_linea_id'::text, true), ''::text))::integer));

CREATE POLICY consumo_admin_policy ON servicios."Consumo"
    AS PERMISSIVE
    FOR ALL
    TO rol_reporte, rol_auditor
    USING (true) WITH CHECK (true);

ALTER TABLE servicios."Consumo" OWNER TO postgres;
GRANT INSERT, TRUNCATE, TRIGGER, DELETE, SELECT, REFERENCES, UPDATE ON TABLE servicios."Consumo" TO postgres;
GRANT INSERT, SELECT ON TABLE servicios."Consumo" TO rol_app;
GRANT SELECT ON TABLE servicios."Consumo" TO rol_reporte;

-- Permisos de esquema
GRANT ALL ON SCHEMA servicios TO postgres;
GRANT USAGE ON SCHEMA servicios TO rol_app;
GRANT USAGE ON SCHEMA servicios TO rol_reporte;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA servicios TO rol_app;


-- =============================================================
-- BLOQUE 9: FOREIGN KEYS CRUZADAS ENTRE ESQUEMAS
--           (se aplican al final cuando todas las tablas ya existen)
-- =============================================================

-- clientes -> clientes (intra-esquema, ya definidas arriba con CASCADE)
ALTER TABLE clientes."Empresa"         ADD CONSTRAINT fk_emp_cli     FOREIGN KEY (id_cliente) REFERENCES clientes."Cliente"(id_cliente) ON DELETE CASCADE;
ALTER TABLE clientes."Persona_Natural" ADD CONSTRAINT fk_per_nat_cli FOREIGN KEY (id_cliente) REFERENCES clientes."Cliente"(id_cliente) ON DELETE CASCADE;

-- lineas -> clientes
ALTER TABLE lineas."Linea" ADD CONSTRAINT fk_lin_cli FOREIGN KEY (id_cliente) REFERENCES clientes."Cliente"(id_cliente);

-- seguridad -> clientes
ALTER TABLE seguridad."Usuario_Sistema" ADD CONSTRAINT fk_usi_cli FOREIGN KEY (id_cliente) REFERENCES clientes."Cliente"(id_cliente);

-- comercial -> lineas
ALTER TABLE comercial."Numero_Amigo"   ADD CONSTRAINT fk_nam_dest FOREIGN KEY (id_linea_destino) REFERENCES lineas."Linea"(id_linea);
ALTER TABLE comercial."Numero_Amigo"   ADD CONSTRAINT fk_nam_orig FOREIGN KEY (id_linea_origen)  REFERENCES lineas."Linea"(id_linea);
ALTER TABLE comercial."Numero_Amigo"   ADD CONSTRAINT fk_nam_prl  FOREIGN KEY (id_promo_linea)   REFERENCES comercial."Promocion_Linea"(id_promo_linea);
ALTER TABLE comercial."Promocion_Linea" ADD CONSTRAINT fk_prl_lin FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea);

-- fidelizacion -> lineas
ALTER TABLE fidelizacion."Historial_Puntos" ADD CONSTRAINT fk_hpu_inv FOREIGN KEY (id_linea_invitada) REFERENCES lineas."Linea"(id_linea);
ALTER TABLE fidelizacion."Historial_Puntos" ADD CONSTRAINT fk_hpu_lin FOREIGN KEY (id_linea)          REFERENCES lineas."Linea"(id_linea);
ALTER TABLE fidelizacion."Puntos_Bonus"     ADD CONSTRAINT fk_pbo_lin FOREIGN KEY (id_linea)          REFERENCES lineas."Linea"(id_linea) ON DELETE CASCADE;

-- finanzas -> lineas
ALTER TABLE finanzas."Bolsillo"        ADD CONSTRAINT fk_bol_lin  FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea) ON DELETE CASCADE;
ALTER TABLE finanzas."Factura"         ADD CONSTRAINT fk_fac_lin  FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."Recarga"         ADD CONSTRAINT fk_rec_lin  FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."T_Presta"        ADD CONSTRAINT fk_tpr_lin  FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."Tarjeta_Recarga" ADD CONSTRAINT fk_tar_lin  FOREIGN KEY (id_linea_cargada) REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."Transaccion"     ADD CONSTRAINT fk_trx_lin  FOREIGN KEY (id_linea)         REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."Transfuzion"     ADD CONSTRAINT fk_trf_dest FOREIGN KEY (id_linea_destino) REFERENCES lineas."Linea"(id_linea);
ALTER TABLE finanzas."Transfuzion"     ADD CONSTRAINT fk_trf_orig FOREIGN KEY (id_linea_origen)  REFERENCES lineas."Linea"(id_linea);

-- servicios -> lineas
ALTER TABLE servicios."Bolsa_Activa" ADD CONSTRAINT fk_bac_lin FOREIGN KEY (id_linea) REFERENCES lineas."Linea"(id_linea);
ALTER TABLE servicios."Consumo"      ADD CONSTRAINT fk_con_lin FOREIGN KEY (id_linea) REFERENCES lineas."Linea"(id_linea);

-- =============================================================
-- FIN DEL DDL
-- =============================================================
