version: '3.8'
services:
  postgres_viva: # nombre servicio
    build: .
    container_name: contenedor-postgres-viva
    restart: always
    command: ["postgres",
      "-c", "shared_preload_libraries=pg_stat_statements,pgaudit",
      "-c", "log_connections=on",
      "-c", "log_statement=ddl",
      "-c", "pgaudit.log=write,ddl",
      "-c", "pgaudit.log_relation=on",
      "-c", "pgaudit.log_parameter=on"
    ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tbdviva
      POSTGRES_DB: bd-viva
    ports:
      - "5433:5432"
    volumes:
      - ./datos_postgres_viva:/var/lib/postgresql/data
      - ./scripts_iniciales:/docker-entrypoint-initdb.d